# Galaxy Video Library & Course Builder
#
# Create your own Galaxy Training Events
#
#

title: GTN Video Library
url: "https://gallantries.github.io"
baseurl: "/video-library"
code_of_conduct: "https://galaxyproject.org/community/coc/"
license:
gtn: "https://training.galaxyproject.org"
image_dir: "assets/images"
gitter: "https://gitter.im/Galaxy-Training-Network/Lobby"

# Support defaults, can be overridden in event definition
support:
  platform: Slack
  link: "https://gtnsmrgsbord.slack.com/"
  join_link: "https://join.slack.com/t/gtnsmrgsbord/shared_invite/zt-x7vinbs1-BA~Kht6N86JBhDq0uTIVdQ"
  general_channel: "#general"
  general_link: "https://gtnsmrgsbord.slack.com/archives/C01MNM98X9V"
  icebreaker_link: "https://gtnsmrgsbord.slack.com/archives/C01EDBVMHBQ"
  icebreaker_channel: "#social"
  feedback_link: "https://gtnsmrgsbord.slack.com/archives/C01NDF5SFH6"
  feedback_channel: "#feedback"

# Video defaults
video:
  platform: YouTube
  url_prefix: "https://youtu.be/" # this will be prepended to the video ids you put in the schedule

default_galaxies:
- server: eu
  tiaas: gtn-tapas
- server: au
  tiaas: gtn-tapas
- server: us
  tiaas: gtn-tapas

exclude:
- course-builder/


# Build settings
markdown: kramdown
lang: en

icon-tag:
    warning: assets/fa/exclamation-triangle.svg #fas fa-exclamation-triangle
    video: assets/fa/video-camera.svg #fas fa-video
    github: assets/fa/github.svg #fab fa-github
    slides: assets/fa/slides.svg
    tutorial: assets/fa/tutorial.svg
    external-link: assets/fa/external-link.svg
    faq: assets/fa/circle-question-regular.svg

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
